# docker compose 실행
# docker compose up 명령어로 전체 실행
# docker-compose up k6 명령어로 부하 테스트만 실행

# K6 대시보드
# 1. 아래 K6_WEB_DASHBOARD / K6_WEB_DASHBOARD_HOST 주석 풀기
# 2. 서비스 재실행
# 3. docker-compose up k6 명령어 실행
# 4. localhost:5665 접속 -> 대시보드 확인
# 5. K6 실행 결과만 보려면 localhost:5665 화면 끄기
# 6. K6_WEB_DASHBOARD / K6_WEB_DASHBOARD_HOST 다시 주석 처리 후  서비스 재실행
# 7. docker-compose up k6 명령어 실행 -> K6 실행 결과 터미널에 보임

# Grafana 대시보드
# 1. 서비스 실행
# 2. localhost:3000 접속 -> 아이디=admin, 비번=admin
# 3. ...

services:
  app:
    build: .
    container_name: teampage-app
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:8.0
    container_name: teampage-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: teampage-redis
    ports:
      - "6379:6379"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana

  k6:
    image: grafana/k6
    ports:
      - "5665:5665"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - influxdb
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - API_VER=${API_VER:-v1}
      # - K6_WEB_DASHBOARD=true
      # - K6_WEB_DASHBOARD_HOST=0.0.0.0
    command: run /scripts/script.js

volumes:
  mysql-data:
  influxdb:
  grafana: